name: img2img-turbo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=12.1
  - numpy>=1.24.4
  - pillow>=9.5.0
  - scipy==1.11.1
  - tokenizers>=0.14.1
  - torchdata>=0.6.1
  - torchmetrics>=1.0.1
  - tqdm>=4.65.0
  - transformers==4.35.2
  - einops>=0.6.1         # from conda-forge
  - dominate              # from conda-forge
  - opencv                # instead of opencv-python
  - pip
  - pip:
      - timm>=0.9.2
      - clip @ git+https://github.com/openai/CLIP.git
      - open-clip-torch>=2.20.0
      - xformers>=0.0.20
      - streamlit-keyup==0.2.0
      - lpips
      - clean-fid
      - peft
      - diffusers==0.25.1
      - gradio==3.43.1
